# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-23 12:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('alias', models.CharField(blank=True, default=models.CharField(max_length=30, verbose_name='Title'), max_length=30, unique=True, verbose_name='Alias')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('author_url', models.URLField(blank=True, verbose_name='Url')),
                ('author_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('content', models.TextField(verbose_name='Content')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='Title')),
                ('url', models.URLField(unique=True, verbose_name='Url')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.URLField(blank=True, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('status', models.BooleanField(choices=[(True, 'Public'), (False, 'Hide')], default=False, verbose_name='Article status')),
                ('password', models.CharField(blank=True, max_length=80, verbose_name='Password')),
                ('alias', models.CharField(blank=True, default=models.CharField(blank=True, max_length=80, verbose_name='Title'), max_length=80, unique=True, verbose_name='Alias')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Pageviews')),
                ('image', models.URLField(blank=True, verbose_name='Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Category')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, verbose_name='Title')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('alias', models.CharField(blank=True, default=models.CharField(blank=True, max_length=80, verbose_name='Title'), max_length=80, unique=True, verbose_name='Alias')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('alias', models.CharField(blank=True, default=models.CharField(max_length=30, verbose_name='Title'), max_length=30, unique=True, verbose_name='Alias')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(blank=True, to='flow.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Post'),
        ),
    ]
