# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-23 11:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_name', models.CharField(max_length=30, verbose_name='Name')),
                ('meta_alias', models.CharField(blank=True, default=models.CharField(max_length=30, verbose_name='Name'), max_length=30, unique=True, verbose_name='Alias')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=30, verbose_name='Author')),
                ('comment_author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('comment_author_url', models.URLField(blank=True, verbose_name='Url')),
                ('comment_author_ip', models.GenericIPAddressField(verbose_name='IP')),
                ('comment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('comment_content', models.TextField(verbose_name='Content')),
                ('comment_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('link_url', models.URLField(unique=True, verbose_name='Url')),
                ('link_description', models.TextField(blank=True, verbose_name='Description')),
                ('link_image', models.URLField(blank=True, verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('post_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('post_title', models.CharField(blank=True, max_length=80, verbose_name='Title')),
                ('post_content', models.TextField(blank=True, verbose_name='Content')),
                ('post_excerpt', models.TextField(blank=True, verbose_name='Excerpt')),
                ('post_status', models.BooleanField(choices=[(True, 'Public'), (False, 'Hide')], default=False, verbose_name='Article status')),
                ('post_password', models.CharField(blank=True, max_length=80, verbose_name='Password')),
                ('post_alias', models.CharField(blank=True, default=models.CharField(blank=True, max_length=80, verbose_name='Title'), max_length=80, unique=True, verbose_name='Alias')),
                ('post_views', models.PositiveIntegerField(default=0, editable=False, verbose_name='Pageviews')),
                ('post_image', models.URLField(blank=True, verbose_name='Image')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Category')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='PostMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(blank=True, max_length=80, verbose_name='Title')),
                ('post_content', models.TextField(blank=True, verbose_name='Content')),
                ('post_alias', models.CharField(blank=True, default=models.CharField(blank=True, max_length=80, verbose_name='Title'), max_length=80, unique=True, verbose_name='Alias')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('post_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30, verbose_name='Name')),
                ('tag_alias', models.CharField(blank=True, default=models.CharField(max_length=30, verbose_name='Name'), max_length=30, unique=True, verbose_name='Alias')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=models.ManyToManyField(blank=True, to='flow.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.Post'),
        ),
    ]
