# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-29 07:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='postmeta',
            old_name='datetime',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flow.Category'),
        ),
    ]
