# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-29 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20161229_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostMeta',
            new_name='Page',
        ),
    ]
